stages:
  - test

run_selenium_tests:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t selenium-tests .
    - docker run --rm selenium-tests
  artifacts:
    paths:
      - target/surefire-reports/
      - target/site/surefire-report.html
    expire_in: 1 week
    when: always
  allow_failure: false
